### ISSUE TITLE
return onSuccess

### ISSUE THREAD

**Issue by Majed-alaswad9** [SaadShaya7/common_state#1]
return onSuccess if empty or notEmpty

static Future<void> multiStateApiCall<T>({
    required FutureResult<T> Function() apiCall,
    required dynamic emit,
    required StateObject state,
    required String stateName,
    Future<void> Function()? preCall,
    Future<void> Function(T data)? onSuccess,
    Future<void> Function(dynamic failure)? onFailure,
    bool Function(T data)? emptyChecker,
    String? emptyMessage,
  }) async {
    await preCall?.call();

    emit(state.updateState(stateName, LoadingState<T>()));

    final result = await apiCall();

    result.fold(
      (l) {
        emit(state.updateState(stateName, FailureState<T>(l)));
        onFailure?.call(l);
      },
      (r) {
        if (_isResponseEmpty(emptyChecker, r)) {
          emit(state.updateState(stateName, EmptyState<T>(emptyMessage)));
          return;
        }
        emit(state.updateState(stateName, SuccessState<T>(r)));
        onSuccess?.call(r);
      },
    );
  }

**Comment by SaadShaya7** [comment]
Applied
